// Central query-key registry so mutations in one domain can invalidate
// related domains without importing each other's hook files (e.g. firing an
// order touches orders + tables + customers + inventory all at once).
export const queryKeys = {
  menu: ['menu'] as const,
  bestSellers: ['menu', 'best-sellers', 'month'] as const,
  bestSellersToday: ['menu', 'best-sellers', 'today'] as const,
  tables: ['tables'] as const,
  stations: ['stations'] as const,
  taxGroups: ['tax-groups'] as const,
  categories: ['categories'] as const,
  menuOnlyQrToken: ['tables', 'menu-qr-token'] as const,
  orders: (params?: unknown) => ['orders', params] as const,
  order: (id: number) => ['orders', id] as const,
  rushForecast: ['orders', 'rush-forecast'] as const,
  inventory: (branchId?: number | null, includeInactive?: boolean) => ['inventory', branchId, includeInactive ?? false] as const,
  lowStockInventory: ['inventory', 'low-stock'] as const,
  inventoryTransactions: (params?: unknown) => ['inventory', 'transactions', params] as const,
  inventoryItemTransactions: (id: number, params?: unknown) => ['inventory', id, 'transactions', params] as const,
  inventoryBatches: (id: number) => ['inventory-batches', id] as const,
  expiringBatches: (days?: number) => ['inventory-expiring', days] as const,
  purchaseOrders: ['purchase-orders'] as const,
  vendors: (includeInactive?: boolean) => ['vendors', includeInactive] as const,
  orderNoteSuggestions: ['order-note-suggestions'] as const,
  recipe: (menuItemId: number) => ['menu-items', menuItemId, 'recipe'] as const,
  recipeCost: (menuItemId: number) => ['menu-items', menuItemId, 'recipe', 'cost'] as const,
  stockTakes: ['stock-takes'] as const,
  stockTake: (id: number) => ['stock-takes', id] as const,
  foodCostReport: ['reports', 'food-cost'] as const,
  varianceReport: (params?: unknown) => ['reports', 'variance', params] as const,
  missingRecipeAlerts: ['reports', 'missing-recipes'] as const,
  stockReport: (params?: unknown) => ['reports', 'stock', params] as const,
  profitReport: (params?: unknown) => ['reports', 'profit', params] as const,
  salesReport: (params?: unknown) => ['reports', 'sales', params] as const,
  taxGstReport: (params?: unknown) => ['reports', 'tax-gst', params] as const,
  crmReport: (params?: unknown) => ['reports', 'crm', params] as const,
  ordersReport: (params?: unknown) => ['reports', 'orders', params] as const,
  customers: (params?: unknown) => ['customers', params] as const,
  customer: (id: number) => ['customers', id] as const,
  crmInsights: ['customers', 'insights'] as const,
  tasks: (params?: unknown) => ['tasks', params] as const,
  notifications: ['notifications'] as const,
  myNotificationPreferences: ['notifications', 'my-preferences'] as const,
  approvals: (params?: unknown) => ['approvals', params] as const,
  staff: (branchId?: number) => ['staff', branchId] as const,
  shifts: (staffId: number) => ['staff', staffId, 'shifts'] as const,
  allShifts: (date: string) => ['staff', 'shifts', date] as const,
  performance: (staffId: number) => ['staff', staffId, 'performance'] as const,
  allPerformance: ['staff', 'performance'] as const,
  attendance: (params?: unknown) => ['attendance', params] as const,
  myAttendance: (periodStart?: string, periodEnd?: string) => ['attendance', 'me', periodStart, periodEnd] as const,
  payrollRuns: (year?: number, month?: number) => ['payroll-runs', year, month] as const,
  payrollRun: (id: number) => ['payroll-runs', id] as const,
  myPayslips: (year?: number) => ['payroll', 'me', 'payslips', year] as const,
  staffLoans: (staffId?: number, status?: string) => ['staff-loans', staffId, status] as const,
  myLoans: ['staff-loans', 'me'] as const,
  branches: ['branches'] as const,
  subscription: ['subscription'] as const,
  settings: ['settings'] as const,
  notificationCategoryPreferences: ['settings', 'notification-preferences'] as const,
  search: (q: string) => ['search', q] as const,
  audit: (params?: unknown) => ['audit', params] as const,
  integrations: ['integrations'] as const,
  whatsAppStatus: ['whatsapp', 'status'] as const,
  rewards: ['rewards'] as const,
  dashboard: (range: unknown) => ['dashboard', range] as const,
  salesForecast: (forecastDays: number) => ['dashboard', 'forecast', forecastDays] as const,
  shiftOptimization: (date: string) => ['staff', 'shift-optimization', date] as const,
  leaveRequests: (status?: string) => ['leave-requests', status] as const,
  myLeaveRequests: (status?: string) => ['leave-requests', 'me', status] as const,
  superAdminTenants: ['superadmin', 'tenants'] as const,
  superAdminTenantSales: (tenantId: number) => ['superadmin', 'tenants', tenantId, 'sales'] as const,
  supportTickets: ['support', 'tickets'] as const,
  supportTicket: (id: number) => ['support', 'tickets', id] as const,
  superAdminTickets: ['superadmin', 'tickets'] as const,
  superAdminTicket: (id: number) => ['superadmin', 'tickets', id] as const,
};
